CREATE TABLE EMPLOYEE(
EMPLOYEEID UNIQUEIDENTIFIER  NOT NULL,
NAME NVARCHAR(150)  NOT NULL,
DOC NVARCHAR(11)  NOT NULL,
REGISTRATION NVARCHAR(10)  NOT NULL,
ADMISSIONDATE DATE NOT NULL,
PRIMARY KEY(EMPLOYEEID))


SELECT * FROM EMPLOYEE